### ISSUE TITLE
Export not finding notebooks in 1.8.x.x

### ISSUE THREAD

**Issue by evanwarner** [LinusCDE/rmWebUiTools#6]
My tablet finally got updated to 1.8.1.1 and the export script no longer finds any documents to sync. My terminal output just reads:
```
INFO: Updating files that have been changed recently. (Does not delete old files.)
INFO: Export only notebooks.
INFO: Fetching file structure...
Done!
```

I don't know enough about the guts of the reMarkable to tell if something changed with how they structure document data, but the `~/.local/share/remarkable/xochitl/` directory still seems to be where it's all located.

`./tree.py --help` and `./paths.py --help` still print out correct information about all my files.

Seems like the 1.8 update is doing more harm than good for a lot of things.

**Comment by evanwarner** [comment]
Ahhh... `./stats.py --help` gives me:
```
Fetching file structure...

ERROR: Unexpeted filetype for "Path/To/One of my Notebooks": notebook
```

**Comment by evanwarner** [comment]
Created a PR to fix this (#7).

**Comment by LinusCDE** [comment]
Thanks for pointing this out and fixing it! Is merged.

I also added an commit to allow the old condition to still work, since many people still seem to be on 1.7 and that will break the program for them.
In about some weeks/months we can probably remove that.

**Comment by evanwarner** [comment]
Awesome, you beat me to it. I had the same thought about backwards compatibility after I submitted and walked away from my computer.
